import { Lato } from "next/font/google";

import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import TopBtn from "./components/TopBtn";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Tourism App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased relative`}>
        <Navbar />
        {children}
        <TopBtn />
        <Footer />
      </body>
    </html>
  );
}
